### PR TITLE
Adapt models to scvi-tools v0.15

### PR DESCRIPTION
**Pull request by jjhong922**
In v0.15.0 scvi-tools will overhaul the data handling strategy to move scvi-tools related metadata to a new wrapper class called `AnnDataManager`. This results in structured and centralized access to data-specific metadata created from `setup_anndata`.

The main obstacle to moving over models to this new version of the code are references to this metadata that will no longer live directly on the AnnData object. Standalone methods like `get_from_registry` will no longer work.

In the cell2location package, there are quite a few uses of `get_from_registry` add the module level/Pyro model level which poses a problem since these classes do not have access to the `AnnDataManager` object, only models inheriting from `BaseModelClass` do.

I propose two potential solutions:
1. Move methods like `LocationModelLinearDependentWMultiExperimentLocationBackgroundNormLevelGeneAlphaPyroModel.compute_expected` up to the model level. If there is code that must live in the module, the model-level function can pass down necessary arguments down to a module-level function.
For example:
`model.compute_expected(samples, adata)` calls a function `module.compute_expected(samples, batch)`, no longer necessitating a call to `get_from_registry` within the module.
2. More simply, these functions can take an `AnnDataManager` object rather than an `AnnData`. For example:
`expected_dict = mod.module.model.compute_expected_per_cell_type(
    mod.samples["post_sample_q05"], mod.adata_manager
)`

Happy to discuss this further, but did not want to touch the deeper code without consulting you!

### CODE REVIEW

**Comment by vitkl** [comment]
Hi @jjhong922 

Thank you very much for this PR.

Does the use of `AnnDataManager` object change the user interface in any way?

I strongly prefer solution number two because the motivation to add that method to `mod.module.model` is that multiple versions of the PyroModel class can be used together with a single user-facing model class. This second solution also looks quite straightforward.

**Comment by jjhong922** [comment]
`_CONSTANTS` can be replaced with `REGISTRY_KEYS`. Alternatively, you are able to configure them to your own constants with the new API.

**Comment by jjhong922** [comment]
> Does the use of AnnDataManager object change the user interface in any way?

No with the exception of our SCANVI model which has a more natural function signature enabled by the change.

> I strongly prefer solution number two because the motivation to add that method to mod.module.model is that multiple versions of the PyroModel class can be used together with a single user-facing model class. This second solution also looks quite straightforward.

Agree the second solution will be far more straightforward. However, it will change the user interface since you are changing the function signature. If the function isn't intended to be called by users (only by model classes) then I think this is more than fine.

**Comment by vitkl** [comment]
@jjhong922 @adamgayoso 

Did the new versions introduce more relevant changes?

**Comment by adamgayoso** [comment]
@vitkl please let us know if you need anything on this PR

**Pull request merged**
